import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import criteriaRouter from "./criteria";
import evidenceRouter from "./evidence";
import blueprintRouter from "./blueprint";
import applyBlueprintRouter from "./applyBlueprint";
import adminBlueprintRouter from "./adminBlueprint";
import adminCasesRouter from "./adminCases";
import adminProspectsRouter from "./adminProspects";
import petitionAdminRouter from "./petitionAdmin";
import petitionClientRouter from "./petitionClient";
import coursesRouter from "./courses";
import dashboardRouter from "./dashboard";
import lessonsRouter from "./lessons";
import notificationsRouter from "./notifications";
import intakeRouter from "./intake";
import stripeRouter from "./stripe";
import adminSeedRouter from "./adminSeed";
import emailRouter from "./email";
import contactRouter from "./contact";
import boothRouter from "./booth";
import adminBoothEventsRouter from "./adminBoothEvents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(criteriaRouter);
router.use(evidenceRouter);
router.use(blueprintRouter);
router.use(applyBlueprintRouter);
router.use(adminBlueprintRouter);
router.use(adminCasesRouter);
router.use(adminProspectsRouter);
router.use(petitionAdminRouter);
router.use(petitionClientRouter);
router.use(coursesRouter);
router.use(dashboardRouter);
router.use(lessonsRouter);
router.use(notificationsRouter);
router.use(intakeRouter);
router.use(stripeRouter);
router.use(adminSeedRouter);
router.use("/email", emailRouter);
router.use(contactRouter);
router.use(boothRouter);
router.use(adminBoothEventsRouter);

export default router;
