export const DISCLAIMER_VERSION = "1.0";

export const LEGAL_DISCLAIMER =
  "Pinnacle³ is a coaching and preparation platform. We are not a law firm and do not " +
  "provide legal advice. Nothing on this platform constitutes legal advice or creates an " +
  "attorney-client relationship. For legal advice regarding your immigration case, please " +
  "consult a licensed immigration attorney.";

export const AI_DISCLAIMER =
  "This content was generated by artificial intelligence based on information you provided. " +
  "AI-generated content may contain errors, omissions, or inaccuracies. You are responsible " +
  "for verifying all information before relying on it or submitting it in any official context. " +
  "Pinnacle³ does not guarantee the accuracy of AI-generated content.";

export const DOCUMENT_DRAFT_WARNING =
  "DRAFT DOCUMENT — This document was prepared with AI assistance. Do not submit to USCIS " +
  "or any government authority without review and certification by a licensed immigration attorney.";

export const RECO_LETTER_NOTE =
  "This is an AI-generated draft for the named recommender's review only. The content does " +
  "not represent the recommender's actual views until personally reviewed, edited, and signed.";

export const COVER_LETTER_WARNING =
  "DRAFT — AI-ASSISTED PETITION LETTER. This document requires review and certification by a " +
  "licensed immigration attorney before submission to USCIS. Do not submit without attorney review.";

export const AI_VARIANTS = {
  analysis:
    "AI analysis — this assessment was generated automatically and may not reflect all relevant factors. Review carefully.",
  lesson:
    "AI-generated lesson. For educational purposes only. Not legal advice. Immigration requirements change — verify with a licensed attorney.",
  document:
    "AI-generated draft. Review all content carefully before sharing. Pinnacle³ is not a law firm.",
  summary:
    "AI-generated summary. Verify against source documents for accuracy.",
  strength:
    "Strength rating is AI-generated. Your attorney may assess this evidence differently.",
} as const;

export type AiVariant = keyof typeof AI_VARIANTS;
