// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pinnacle-home/AccessibilityReadability.tsx": () => import("../components/mockups/pinnacle-home/AccessibilityReadability.tsx"),
  "./components/mockups/pinnacle-home/InformationHierarchy.tsx": () => import("../components/mockups/pinnacle-home/InformationHierarchy.tsx"),
  "./components/mockups/pinnacle-home/InteractionAffordance.tsx": () => import("../components/mockups/pinnacle-home/InteractionAffordance.tsx")
};
