import { pgTable, text, integer, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const visaCriteriaTable = pgTable("visa_criteria", {
  id: text("id").primaryKey(),
  visaPath: text("visa_path").notNull(),
  criteriaCode: text("criteria_code").notNull(),
  criteriaName: text("criteria_name").notNull(),
  legalStandard: text("legal_standard").notNull(),
  folderName: text("folder_name").notNull(),
  displayOrder: integer("display_order").notNull(),
  isCommon: boolean("is_common").default(true),
  uploadGuidance: text("upload_guidance"),
});

export const insertVisaCriterionSchema = createInsertSchema(visaCriteriaTable);
export type InsertVisaCriterion = z.infer<typeof insertVisaCriterionSchema>;
export type VisaCriterion = typeof visaCriteriaTable.$inferSelect;

export const VISA_CRITERIA_SEED: InsertVisaCriterion[] = [
  // ── EB-1A ──────────────────────────────────────────────────────────────────
  // Display order matches driveFolderConfig.ts EB1A_CRITERIA index order.
  // Original DB had Exhibitions at 10, Critical role at 7, High salary at 8,
  // Commercial success at 9 — reordered here to match folder index 6→7, 7→8, 8→9, 9→10.
  {
    id: "EB1A-01",
    visaPath: "eb1a",
    criteriaCode: "01",
    criteriaName: "Awards and prizes",
    legalStandard: "Documentation of the alien's receipt of nationally or internationally recognized prizes or awards for excellence in the field of endeavor.",
    folderName: "EB1A-01_Awards_and_Prizes",
    displayOrder: 1,
    isCommon: true,
    uploadGuidance: "Upload award certificates, nomination letters, trophy photos, and any press coverage specifically about receiving the award. Include documentation showing how recipients are selected and what percentage of professionals in your field receive this recognition.",
  },
  {
    id: "EB1A-02",
    visaPath: "eb1a",
    criteriaCode: "02",
    criteriaName: "Membership",
    legalStandard: "Documentation of the alien's membership in associations in the field which require outstanding achievements of their members, as judged by recognized national or international experts.",
    folderName: "EB1A-02_Membership",
    displayOrder: 2,
    isCommon: true,
    uploadGuidance: "Upload your membership certificate or confirmation letter, the organization's membership criteria page, and any documentation showing the selection process. Evidence that membership requires a vote by existing members or peer review is especially valuable.",
  },
  {
    id: "EB1A-03",
    visaPath: "eb1a",
    criteriaCode: "03",
    criteriaName: "Press and media",
    legalStandard: "Published material about the alien in professional or major trade publications or other major media, relating to the alien's work in the field.",
    folderName: "EB1A-03_Press_and_Media",
    displayOrder: 3,
    isCommon: true,
    uploadGuidance: "Upload the full article or interview (not just the headline), documentation of the publication's circulation or reach, and evidence that the coverage is specifically about you and your work — not just a mention. Screenshots of online articles with view counts or domain authority help.",
  },
  {
    id: "EB1A-04",
    visaPath: "eb1a",
    criteriaCode: "04",
    criteriaName: "Judging others",
    legalStandard: "Evidence of the alien's participation, either individually or on a panel, as a judge of the work of others in the same or an allied field.",
    folderName: "EB1A-04_Judging_Others",
    displayOrder: 4,
    isCommon: true,
    uploadGuidance: "Upload the formal invitation letter naming you as a judge or reviewer, the event program or panel description, any certificates of participation, and documentation showing the scope of what you reviewed (number of submissions, prestige of the event or journal).",
  },
  {
    id: "EB1A-05",
    visaPath: "eb1a",
    criteriaCode: "05",
    criteriaName: "Original contributions",
    legalStandard: "Evidence of the alien's original scientific, scholarly, artistic, athletic, or business-related contributions of major significance in the field.",
    folderName: "EB1A-05_Original_Contributions",
    displayOrder: 5,
    isCommon: true,
    uploadGuidance: "Upload patents, published papers citing your work, letters from other professionals describing how they have adopted your methods, performance data showing impact, and any industry recognition of your specific contribution. The stronger the evidence that others have built on your work, the better.",
  },
  {
    id: "EB1A-06",
    visaPath: "eb1a",
    criteriaCode: "06",
    criteriaName: "Scholarly articles",
    legalStandard: "Evidence of the alien's authorship of scholarly articles in the field, in professional or major trade publications or other major media.",
    folderName: "EB1A-06_Scholarly_Articles",
    displayOrder: 6,
    isCommon: true,
    uploadGuidance: "Upload the full text of each published article, the acceptance or publication confirmation email, the journal or conference homepage showing it is a recognized venue, and citation records if available. Include articles where you are a named author — co-authorship counts.",
  },
  {
    id: "EB1A-10",
    visaPath: "eb1a",
    criteriaCode: "10",
    criteriaName: "Artistic exhibitions",
    legalStandard: "Evidence of the display of the alien's work in the field at artistic exhibitions or showcases.",
    folderName: "EB1A-10_Exhibitions",
    displayOrder: 7,
    isCommon: false,
    uploadGuidance: "Upload exhibition catalogs, invitations, photographs of your work on display, press coverage of the exhibition, and documentation of the venue's reputation. Evidence of juried or curated exhibitions is stronger than open-call shows.",
  },
  {
    id: "EB1A-07",
    visaPath: "eb1a",
    criteriaCode: "07",
    criteriaName: "Critical role",
    legalStandard: "Evidence that the alien has performed in a leading or critical role for organizations or establishments that have a distinguished reputation.",
    folderName: "EB1A-07_Critical_Role",
    displayOrder: 8,
    isCommon: true,
    uploadGuidance: "Upload your offer letter or employment contract showing your title, an org chart placing you in the organization, performance reviews or letters from supervisors describing your responsibilities, and documentation of the organization's size, revenue, or distinguished reputation.",
  },
  {
    id: "EB1A-08",
    visaPath: "eb1a",
    criteriaCode: "08",
    criteriaName: "High salary",
    legalStandard: "Evidence that the alien has commanded a high salary or other significantly high remuneration for services, in relation to others in the field.",
    folderName: "EB1A-08_High_Salary",
    displayOrder: 9,
    isCommon: true,
    uploadGuidance: "Upload your most recent pay stubs (last 3 months), your offer letter showing base salary and total compensation, any bonus or equity documentation, and your W-2 or equivalent. We will compare your compensation to Bureau of Labor Statistics data for your role and location.",
  },
  {
    id: "EB1A-09",
    visaPath: "eb1a",
    criteriaCode: "09",
    criteriaName: "Commercial success",
    legalStandard: "Evidence of commercial successes in the performing arts, as shown by box office receipts or record, cassette, compact disk, or video sales.",
    folderName: "EB1A-09_Commercial_Success",
    displayOrder: 10,
    isCommon: false,
    uploadGuidance: "Upload box office records, streaming numbers, album sales figures, ticket sales, or any official documentation of commercial performance. Include industry benchmark data showing how your results compare to peers in the performing arts.",
  },

  // ── NIW ────────────────────────────────────────────────────────────────────
  // Aligned to the 3 Dhanasar prongs which match the 3 NIW drive folders.
  // NIW-01→prong1, NIW-02→prong2 (repurposed), NIW-03→prong3 (repurposed).
  // NIW-04 through NIW-08 remain in DB but have no corresponding drive folders.
  {
    id: "NIW-01",
    visaPath: "niw",
    criteriaCode: "01",
    criteriaName: "Substantial merit and national importance",
    legalStandard: "The proposed endeavor has substantial merit and national importance in business, science, technology, culture, health, or education, with impact that is national in scope.",
    folderName: "NIW-01_Substantial_Merit",
    displayOrder: 1,
    isCommon: true,
    uploadGuidance: "Upload research papers, project descriptions, government reports referencing your field, news articles about the national importance of your work, and any letters from institutions or agencies describing the broader impact of your contributions.",
  },
  {
    id: "NIW-02",
    visaPath: "niw",
    criteriaCode: "02",
    criteriaName: "Well positioned to advance",
    legalStandard: "The petitioner is well positioned to advance the proposed endeavor based on education, skills, knowledge, and record of success in the field.",
    folderName: "NIW-02_National_Importance",
    displayOrder: 2,
    isCommon: true,
    uploadGuidance: "Upload your full CV, degrees and transcripts, publications, awards, letters from collaborators confirming your expertise, and any evidence of past success in advancing your proposed endeavor.",
  },
  {
    id: "NIW-03",
    visaPath: "niw",
    criteriaCode: "03",
    criteriaName: "Balance of factors",
    legalStandard: "On balance, waiving the job offer and labor certification requirement serves the national interest of the United States, as the petitioner's contributions outweigh the national interest in the labor certification process.",
    folderName: "NIW-03_Well_Positioned",
    displayOrder: 3,
    isCommon: true,
    uploadGuidance: "Upload evidence that your work uniquely benefits the United States — such as partnerships with US institutions, funding from US government agencies, or documentation that your specific expertise is scarce among US workers. Letters from US employers or institutions are particularly helpful.",
  },
  {
    id: "NIW-04",
    visaPath: "niw",
    criteriaCode: "04",
    criteriaName: "Education and credentials",
    legalStandard: "Advanced degree or exceptional ability demonstrated through academic credentials and professional qualifications.",
    folderName: "NIW-04_Education_Credentials",
    displayOrder: 4,
    isCommon: true,
    uploadGuidance: null,
  },
  {
    id: "NIW-05",
    visaPath: "niw",
    criteriaCode: "05",
    criteriaName: "Track record",
    legalStandard: "Past contributions and demonstrated expertise showing a track record of success in the field of endeavor.",
    folderName: "NIW-05_Track_Record",
    displayOrder: 5,
    isCommon: true,
    uploadGuidance: null,
  },
  {
    id: "NIW-06",
    visaPath: "niw",
    criteriaCode: "06",
    criteriaName: "Future plan",
    legalStandard: "A detailed and credible plan for the proposed endeavor in the United States and the benefits it will bring.",
    folderName: "NIW-06_Future_Plan",
    displayOrder: 6,
    isCommon: true,
    uploadGuidance: null,
  },
  {
    id: "NIW-07",
    visaPath: "niw",
    criteriaCode: "07",
    criteriaName: "Support letters",
    legalStandard: "Letters from experts and organizations with firsthand knowledge confirming the national interest and the petitioner's standing.",
    folderName: "NIW-07_Support_Letters",
    displayOrder: 7,
    isCommon: true,
    uploadGuidance: null,
  },
  {
    id: "NIW-08",
    visaPath: "niw",
    criteriaCode: "08",
    criteriaName: "Balance of factors",
    legalStandard: "On balance, waiving the job offer and labor certification requirement serves the national interest of the United States.",
    folderName: "NIW-08_Balance_of_Factors",
    displayOrder: 8,
    isCommon: true,
    uploadGuidance: null,
  },

  // ── O-1A ───────────────────────────────────────────────────────────────────
  // O1A display_order matches driveFolderConfig.ts O1A_CRITERIA index perfectly.
  {
    id: "O1A-01",
    visaPath: "o1",
    criteriaCode: "01",
    criteriaName: "Awards and prizes",
    legalStandard: "Documentation of the beneficiary's receipt of nationally or internationally recognized prizes or awards for excellence in the field.",
    folderName: "O1A-01_Awards_and_Prizes",
    displayOrder: 1,
    isCommon: true,
    uploadGuidance: "Upload award certificates, nomination letters, and documentation of the award's selectivity and national or international recognition. Include evidence of how recipients are chosen.",
  },
  {
    id: "O1A-02",
    visaPath: "o1",
    criteriaCode: "02",
    criteriaName: "Membership",
    legalStandard: "Documentation of the beneficiary's membership in associations that require outstanding achievements as judged by recognized experts.",
    folderName: "O1A-02_Membership",
    displayOrder: 2,
    isCommon: true,
    uploadGuidance: "Upload membership confirmation, the organization's selection criteria, and evidence that membership requires outstanding achievement as judged by recognized experts in the field.",
  },
  {
    id: "O1A-03",
    visaPath: "o1",
    criteriaCode: "03",
    criteriaName: "Press coverage",
    legalStandard: "Published material in professional or major trade publications about the beneficiary and the beneficiary's work.",
    folderName: "O1A-03_Press_Coverage",
    displayOrder: 3,
    isCommon: true,
    uploadGuidance: "Upload full copies of articles or interviews about you and your work, with documentation of the publication's reach and audience. Coverage in major trade publications or mainstream media carries the most weight.",
  },
  {
    id: "O1A-04",
    visaPath: "o1",
    criteriaCode: "04",
    criteriaName: "Judging",
    legalStandard: "Evidence of the beneficiary's participation as a judge of the work of others in the same or allied field.",
    folderName: "O1A-04_Judging",
    displayOrder: 4,
    isCommon: true,
    uploadGuidance: "Upload your formal invitation to judge, the event or journal description, any participation certificate, and evidence of the scope and prestige of what you reviewed.",
  },
  {
    id: "O1A-05",
    visaPath: "o1",
    criteriaCode: "05",
    criteriaName: "Original contributions",
    legalStandard: "Evidence of the beneficiary's original scientific, scholarly, or business-related contributions of major significance.",
    folderName: "O1A-05_Original_Contributions",
    displayOrder: 5,
    isCommon: true,
    uploadGuidance: "Upload patents, letters from peers describing the impact of your contributions, citations, adoption evidence, and any industry or academic recognition of your specific work.",
  },
  {
    id: "O1A-06",
    visaPath: "o1",
    criteriaCode: "06",
    criteriaName: "Scholarly articles",
    legalStandard: "Evidence of the beneficiary's authorship of scholarly articles in professional journals or other major media.",
    folderName: "O1A-06_Scholarly_Articles",
    displayOrder: 6,
    isCommon: true,
    uploadGuidance: "Upload full article texts, publication confirmations, journal or conference credentials, and citation records. Co-authored articles where you are a named author are included.",
  },
  {
    id: "O1A-07",
    visaPath: "o1",
    criteriaCode: "07",
    criteriaName: "Critical or essential role",
    legalStandard: "Evidence of the beneficiary's performance in a critical or essential role for distinguished organizations.",
    folderName: "O1A-07_Critical_Role",
    displayOrder: 7,
    isCommon: true,
    uploadGuidance: "Upload your title documentation, org chart, letters describing your specific responsibilities, and evidence of the organization's distinguished reputation — such as revenue figures, industry rankings, or press coverage.",
  },
  {
    id: "O1A-08",
    visaPath: "o1",
    criteriaCode: "08",
    criteriaName: "High remuneration",
    legalStandard: "Evidence of the beneficiary's high salary or other remuneration for services compared to others in the field.",
    folderName: "O1A-08_High_Remuneration",
    displayOrder: 8,
    isCommon: true,
    uploadGuidance: "Upload pay stubs, offer letter, W-2 or equivalent, bonus and equity documentation, and any employer compensation statements. We compare your earnings to industry benchmarks for your role.",
  },
];
