export const LEGAL_DISCLAIMER =
  "Pinnacle³ is not a law firm and does not provide legal advice. All content, analysis, and documents are for informational and educational purposes only. Immigration laws change frequently — always consult a licensed immigration attorney before taking any action.";

export const AI_VARIANTS = {
  analysis:
    "This analysis was generated by AI and may contain errors or omissions. It does not constitute legal advice. Verify all findings with a qualified immigration attorney before relying on them.",
  lesson:
    "This lesson content was generated by AI. Immigration laws and USCIS policies change frequently. Treat this as educational material only — not legal guidance.",
  document:
    "This document is an AI-generated draft. It must be reviewed, edited, and approved by a licensed immigration attorney before any official submission or use.",
  summary:
    "This summary was generated by AI and may not reflect your complete profile or legal standing. Consult a licensed attorney for an accurate case assessment.",
  strength:
    "Strength assessments are AI-generated estimates based on general patterns and do not guarantee petition outcomes. Results vary based on individual circumstances.",
} as const;

export type AIVariant = keyof typeof AI_VARIANTS;
